# Generated by Django 6.0.3 on 2026-03-07 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
    ]
